server {
    listen 443 ssl;
    server_name myapp.local;

    ssl_certificate       /etc/nginx/certs/myapp.local.pem;
    ssl_certificate_key   /etc/nginx/certs/myapp.local-key.pem;


    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
} 

server {
    listen 80;
    server_name myapp.local;
    return 301 https://$host$request_uri;
}