version: "3.9"

services:

  mongo:
    image: mongo:6.0
    container_name: mongo
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  mongo-data: